# Database tables
TABLE_NAME = 'ANALYTICS.PLATINUM.EVENT_REGISTRATION_EXPORT'
EVENT_TABLE_NAME = 'ANALYTICS.PLATINUM.EVENT_REGISTRATIONS'
AUDIT_TABLE_NAME = 'ANALYTICS.PLATINUM.APPLICATION_AUDIT_LOG'

# Audit types
AUDIT_TYPE_LOAD_APP = 'load_app'
AUDIT_TYPE_EXECUTE_SEARCH = 'execute_search'
AUDIT_TYPE_DOWNLOAD_REPORT = 'download_report'

# Column names
REGISTRATION_ID_COL = 'REGISTRATION_ID'
PROJECT_ID_COL = 'PROJECT_ID'
COMPANY_ID_COL = 'COMPANY_ID'
EVENT_NAME_COLUMN = 'EVENT_NAME'
USER_TITLE_COLUMN = 'TITLE'
REGISTRATION_COUNT_COLUMN = 'REGISTRATION_COUNT'
OPT_IN_LF_NEWS_COL = 'OPT_IN_LF_NEWS_ANNOUNCEMENTS'
OPT_IN_TNC_PROMOS_COL = 'OPT_IN_TNC_PROMOTIONS'
IS_SPEAKER_COL = 'IS_SPEAKER'
IS_LF_MEMBER_COL = 'IS_CURRENT_LF_MEMBER'
IS_PROJECT_MEMBER_COL = 'IS_CURRENT_PROJECT_MEMBER'
REGISTRATION_DATE_COLUMN = 'REGISTRATION_DATE'

# UI constants
DEFAULT_EVENT_SELECTION = '  --- Select Event ---  '
CHART_TYPES = ['Line Chart', 'Bar Chart', 'Mark Circles']
OPT_SHOW_ALL_TEXT = 'Show All'
OPT_IN_ONLY_TXT = 'Show Opt-In Records Only'
OPT_OUT_ONLY_TXT = 'Show Did Not Opt-In Records Only'
IS_SPEAKER_TEXT = 'Speakers'
IS_NOT_SPEAKER_TEXT = 'Attendees Only'
IS_LF_MEMBER_TEXT = 'LF Member'
IS_NOT_LF_MEMBER_TEXT = 'Not a LF Member'
IS_PROJECT_MEMBER_TEXT = 'Project Member'
IS_NOT_PROJECT_MEMBER_TEXT = 'Not a Project Member'